# Generated by Django 3.0.7 on 2020-11-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nomUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=12)),
                ('passcode', models.CharField(max_length=6)),
                ('is_bloqueado', models.BooleanField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dui', models.CharField(max_length=50)),
                ('isss', models.CharField(max_length=50)),
                ('nup', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('estadoCivil', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaCuenta',
            fields=[
                ('idEstadisticas', models.IntegerField(primary_key=True, serialize=False)),
                ('cambioClave', models.IntegerField()),
                ('cambioRol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('numPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=75)),
                ('respuesta', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(max_length=50)),
                ('estadoSolicitud', models.BooleanField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idEstadisticas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.EstadisticaCuenta'),
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Cuenta')),
                ('numPregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Pregunta')),
            ],
        ),
    ]
