# Generated by Django 3.0.7 on 2020-11-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticacuenta',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bancopregunta',
            unique_together={('nomUsuario', 'numPregunta')},
        ),
    ]
