# Generated by Django 3.0.7 on 2020-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_change_date',
            field=models.DateTimeField(null=True),
        ),
    ]
