# Generated by Django 3.0.7 on 2020-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0002_auto_20201127_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='passcode',
            field=models.CharField(max_length=100),
        ),
    ]
