# Generated by Django 3.0.7 on 2020-11-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0002_auto_20201120_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticacuenta',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
