# Generated by Django 3.0.7 on 2020-12-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0002_usuario_password_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancopregunta',
            name='nomUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bancopregunta',
            name='numPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.Pregunta'),
        ),
        migrations.AlterField(
            model_name='estadisticacuenta',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.Municipio'),
        ),
    ]
