# Generated by Django 3.0.7 on 2020-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0003_auto_20201205_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
