# Generated by Django 3.0.7 on 2020-11-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nomUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=12)),
                ('passcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dui', models.CharField(max_length=50)),
                ('isss', models.CharField(max_length=50)),
                ('nup', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('estadoCivil', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('nomUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='ERH',
            fields=[
                ('idERH', models.IntegerField(primary_key=True, serialize=False)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaCuenta',
            fields=[
                ('idEstadisticas', models.IntegerField(primary_key=True, serialize=False)),
                ('cambioClave', models.IntegerField()),
                ('cambioRol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionCrud',
            fields=[
                ('idOpcion', models.IntegerField(primary_key=True, serialize=False)),
                ('numCrud', models.IntegerField()),
                ('descripCrud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('numPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=75)),
                ('respuesta', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='PuestosDT',
            fields=[
                ('idPuesto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePuesto', models.CharField(max_length=50)),
                ('descripPuesto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=50)),
                ('descripRol', models.CharField(max_length=200)),
                ('idERH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ERH')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('idUnidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=50)),
                ('descripUnidad', models.CharField(max_length=200)),
                ('idPuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PuestosDT')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSolicitud', models.CharField(max_length=50)),
                ('estadoSolicitud', models.BooleanField()),
                ('idERH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ERH')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RolOpcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.OpcionCrud')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='puestosdt',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Rol'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idEstadisticas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.EstadisticaCuenta'),
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Cuenta')),
                ('numPregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pregunta')),
            ],
        ),
    ]
