# Generated by Django 3.0.7 on 2020-11-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaCuenta',
            fields=[
                ('idEstadisticas', models.IntegerField(primary_key=True, serialize=False)),
                ('cambioClave', models.IntegerField()),
                ('cambioRol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('numPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=75)),
                ('respuesta', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nomUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=12)),
                ('passcode', models.CharField(max_length=6)),
                ('is_bloqueado', models.BooleanField()),
                ('idEstadisticas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.EstadisticaCuenta')),
            ],
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Cuenta')),
                ('numPregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Pregunta')),
            ],
        ),
    ]
