# Generated by Django 3.0.7 on 2020-11-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('idUnidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=50)),
                ('descripUnidad', models.CharField(max_length=200)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rol.Rol')),
            ],
        ),
    ]
