# Generated by Django 3.0.7 on 2020-12-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadOrganizacional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='idRol',
        ),
    ]
