# Generated by Django 3.0.7 on 2020-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadOrganizacional', '0002_remove_unidadorganizacional_idrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='idUnidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
