# Generated by Django 3.0.7 on 2020-11-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionCrud',
            fields=[
                ('idOpcion', models.IntegerField(primary_key=True, serialize=False)),
                ('numCrud', models.IntegerField()),
                ('descripCrud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=50)),
                ('descripRol', models.CharField(max_length=200)),
                ('is_activo', models.BooleanField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Empleado.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RolOpcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rol.OpcionCrud')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rol.Rol')),
            ],
        ),
    ]
