# Generated by Django 3.0.7 on 2020-11-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dui', models.CharField(max_length=50)),
                ('isss', models.CharField(max_length=50)),
                ('nup', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('estadoCivil', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('nomUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cuenta.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(max_length=50)),
                ('estadoSolicitud', models.BooleanField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Empleado.Empleado')),
            ],
        ),
    ]
