# Generated by Django 3.0.7 on 2020-12-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rol', '0002_rol_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolopcion',
            name='idOpcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rol.OpcionCrud'),
        ),
        migrations.AlterField(
            model_name='rolopcion',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rol.Rol'),
        ),
        migrations.AlterField(
            model_name='rolusuario',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolusuario',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rol.Rol'),
        ),
    ]
