# Generated by Django 3.0.7 on 2020-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rol', '0003_auto_20201205_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolusuario',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
